geometry:
  grid:
    name: S360x180
    domain:
      type: global
      west: -180
  landmask:
    filename: landmask.nc
  rossby radius file: rossby_radius.dat

analysis variables: &vars [sea_surface_temperature]

background:
  state variables: *vars
  date: 2018-04-15T00:00:00Z # date doesn't matter here, just pick something
  filename: bkg.nc

background error:
  covariance model: umdsstCovar
  bump:
    verbosity: main
    datadir: bump
    prefix: bump_sst
    method: cor
    strategy: specific_univariate
    mask_check: 1
    network: 1
    new_nicas: 1
    ntry: 3
    resol: 6.0
    mpicom: 2
    nc1max: 100000

  correlation lengths:
    base value: 0.0
    rossby mult: 1.0
    min grid mult: 1.5
    #min value: 25.0e3
    #max value:

